### ISSUE TITLE
Can't install (Windows 10)

### ISSUE THREAD

**Issue by KomplexMojo** [OpenZeppelin/starter-kit-tutorial#34]
Following the install instructions I can't install on Windows 10.  Looks like it can't find the WebSocket-Node.git

1225 verbose stack Error: spawn git ENOENT
1225 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
1225 verbose stack     at onErrorNT (internal/child_process.js:456:16)
1225 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
1226 verbose cwd D:\OpenZeppelin
1227 verbose Windows_NT 10.0.17763
1228 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@openzeppelin/cli@2.5.3"
1229 verbose node v12.13.1
1230 verbose npm  v6.12.1
1231 error code ENOENT
1232 error syscall spawn git
1233 error path git
1234 error errno ENOENT
1235 error enoent Error while executing:
1235 **error enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git**
1235 error enoent
1235 error enoent
1235 error enoent spawn git ENOENT
1236 error enoent This is related to npm not being able to find a file.
1237 verbose exit [ 1, true ]

**Comment by KomplexMojo** [comment]
Using yarn.

PS D:\OpenZeppelin> yarn global add @openzeppelin/cli@2.5.3
yarn global v1.21.0
[1/4] Resolving packages...
warning @openzeppelin/cli > @types/web3@1.2.2: This is a stub types definition. web3 provides its own type definitions, so you do not need this installed.
warning @openzeppelin/cli > truffle-config@1.1.16: WARNING: This package has been renamed to @truffle/config.
warning @openzeppelin/cli > truffle-config > truffle-provider@0.1.16: WARNING: This package has been renamed to @truffle/provider.
warning @openzeppelin/cli > truffle-config > truffle-error@0.0.5: WARNING: This package has been renamed to @truffle/error.
warning @openzeppelin/cli > @types/web3 > web3 > web3-core > @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
warning @openzeppelin/cli > truffle-config > truffle-provider > truffle-interface-adapter@0.2.5: WARNING: This package has been renamed to @truffle/interface-adapter.
**error Couldn't find the binary git**
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by KomplexMojo** [comment]
I see that the latest version is 2.6.0.  Tried to install.  Same issue.

**Comment by ylv-io** [comment]
Hey/ @KomplexMojo! Sorry to hear about your experience.  Have you tried [windows build tools](https://www.npmjs.com/package/windows-build-tools)? They helped many people on windows to install node dependencies.

**Comment by KomplexMojo** [comment]
Thanks for the feedback.  I'm technical but fairly new to this so I'm stumbling around a bit.

I do have windows build tools installed but I re-installed it just in case.

Could this be a permissions thing on the Web-Sockets git?

I tried.

$ git ls-remote git@github.com:web3-js/WebSocket-Node.git
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
**git@github.com: Permission denied (publickey).**
**fatal: Could not read from remote repository.**

Please make sure you have the correct access rights and the repository exists.

**Comment by KomplexMojo** [comment]
same as this issue.  git dependency in install code:  https://github.com/ethereum/web3.js/issues/3071

**Comment by abcoathup** [comment]
The web3 issue suggests installing Git for Windows  

Alternatively you may want to consider using Windows Subsystem for Linux (WSL).  I previously developed on Windows 7 & 10 but have a much easier time with WSL.

**Comment by abcoathup** [comment]
@KomplexMojo I assume the issue is that you need to install Git.

For setting up for Solidity Smart Contract Development on Windows please see the following guide:
https://forum.openzeppelin.com/t/solidity-smart-contract-development-on-windows/2110

There is an Issue with OpenZeppelin Network.js on Windows https://github.com/OpenZeppelin/openzeppelin-network.js/issues/27 though you can install using Git Bash terminal if using native Windows.
